# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 - master 
variables:
  # tag: '$(Build.BuildId)'
  ImageName: 'surekhadock2020/azuredevops-ci:$(tag)'
steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     containerRegistry: 'Docker Service Connection'
     repository: 'surekhadock2020/azurecipipelineimage'
     command: build
     Dockerfile: '**/Dockerfile'
 - task: Docker@2 
   displayName: 'Push the image'
   inputs:
     command: 'Push'
     containerRegistry: 'Docker Service Connection'
     repository: 'surekhadock2020/azurecipipelineimage'
    
