# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
stages:
- stage: Build
  displayName: Build an Image
  jobs:
  - job: Build    
      steps:
      - task: Docker@2
      displayName: 'Build an Image from Dockerfile'
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'

