# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 - master 
variables:
  # tag: '$(Build.BuildId)'
  ImageName: 'surekhadock2020/azuredevops-ci:$(tag)'
steps:
 - task: Docker@1 
   displayName: 'Build an image'
   inputs:
    containerRegistry: 'Docker Service Connection'
    repository: 'surekhadock2020'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
