# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 - master 
pool:
 - vmImage: 'Ubuntu-16.04'
variables:
  tag: '$(Build.BuildId)'
  ImageName: 'surekhadock2020/azuredevops-ci:$(tag)'
steps:
 - task: Docker@1 
   displayName: 'Build an image'
   inputs:
     containerregistrytype: 'container Registry'
     dockerRegistryEndpoint: 'Docker Hub'
     imageName: $('ImageName')
     command: build an image
     dockerFile: '**/Dockerfile'
     includeLatestTag: true
 - task: Docker@1
   displayName: Login
   inputs:
     containerregistrytype: 'container Registry'
     dockerRegistryEndpoint: 'Docker Hub'
     command: login
 - task: Docker@2
   displayName: 'Push an image'
   inputs:
     command: push an image
     imageName: $('ImageName')